### ISSUE TITLE
Do you plan to share your code?

### ISSUE THREAD

**Issue by EwanDawson** [ErikOnBike/CodeParadise#1]
Hi Erik,

I watched your introduction to CodeParadise video on YouTube. I'm also interested in using the browser as the interface to a Pharo image. Are you planning to push code to this repo soon?

Regards,
Ewan

**Comment by ErikOnBike** [comment]
Hi Ewan,

Yes, probably… ;-)

’Soon’ is why I did not write ’Yes of course’. It is my intention to put it all on GitHub, but at the moment it is a bit too volatile. Since I’m working on this in my limited spare time, progress is relative slow. I’m adding some test code and refactor some stuff and will then publish. Still it will remain fragile. A lot is still missing.

Please stay tuned!

Regards,
Erik

**Comment by ErikOnBike** [comment]
@EwanDawson the code is (finally ;-)) available. Please see the README for explanation on getting started.
