### ISSUE TITLE
Missing module CpSystemPlugin when loading client-environment.image

### ISSUE THREAD

**Issue by walter248A** [ErikOnBike/CodeParadise#15]
Great concept, great documentation!  

The console shows an error message coming from SqueakJS when loading the client-environment.image:  "missing module: CpSystemPlugin".  Perhaps this plugin was available in previous versions and omitted by mistake from the current one.  Is there somewhere to download this plugin?

Good luck, I wish you all the best.

**Comment by ErikOnBike** [comment]
@walter248A Oops...I have completely missed/overlooked this issue. This has been open for months. I am really sorry.

I hope you have been able to use CodeParadise nonetheless. The plugin you mention is part of the ClientEnvironment (see https://github.com/ErikOnBike/CP-ClientEnvironment) and has been present since the beginning. I have not received other mentions of this issue. I am using CodeParadise in production systems (typically in combination with Nginx) and it is always available/loaded. Not sure what happened in your case.

Do you use a special setup? Or any particular browser?

**Comment by ErikOnBike** [comment]
@walter248A since I have not received any more messages indicating this is a current issue, I'm closing it. Please re-open if you still encounter problems.
