### ISSUE TITLE
SlSelect not showing selected value

### ISSUE THREAD

**Issue by dahoward** [ErikOnBike/CodeParadise#16]
Erik,

I just updated to current versions of Cp and Shoelace (for Shoelace, I had stayed at shoelace beta.64 to keep SlDialog working properly but I recently decided to just stop using SlDialogs--that was the issue we talked about over the summer).  I hadn't updated Cp since October 8.

Now SlSelect is not showing the selected value.  It works fine otherwise, dropdown shows items properly, checkmark appears next the the selected one, but nothing displays in the field.  If I select a new person (value is ID, display is the person's name), the underlying value that I use programmatically is the newly selected ID, but nothing again is displayed in the SlSelect field.

Can you try to replicate?  If yours works, then something's wrong on my end.  Perhaps you could add the method CpShoelaceExamplesClientBehavior>>exampleSelect for grins.

I did see at the bottom of the Select example on shoelace.style that its dependencies include <sl-popup> which Cp doesn't implement but I have no idea if that's a recently added dependency or if that has any relevance.  As I said, SlSelects were working fine up until my recent upgrading activities so I suspect something has changed to cause this behavior.

Thanks so much,
-Don

**Comment by ErikOnBike** [comment]
Good catch. I'll look into it coming days (no time today unfortunately).

**Comment by dahoward** [comment]
Thanks, Erik.  Great news on moving Cp into Pharo 10!

**Comment by ErikOnBike** [comment]
Hi Don,

It turns out it is not possible within SlSelect to have an HTML content for the label (of the SlMenuItem it is showing). In a previous version I did some 'manual' optimisations when setting the label and it would (on regular text) result in calling #labelText: for a SlMenuItem. This optimisation is removed. So to fix your code you have to manually choose #labelText:. If you (like me) use `SlMenuItem value: #first label: 'First'` please replace it by `SlMenuItem value: #first labelText: 'First'`. That should fix it. Please pull the latest version first, since I added this method just now. HTH.

For some more details also see this Shoelace issue: https://github.com/shoelace-style/shoelace/issues/484

BTW I also added SlSelect to the examples as per your request ;-)

**Comment by dahoward** [comment]
Thank you so much!  That did the trick.
